version: '3'
services:
  jekyllbuild:
    build:
      context: .
      args:
        build_command: "jekyll build --watch"
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
      - 35729:35729
  nginx:
    image: nginx
    volumes:
      - "./build:/var/www/public"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html/404.html:/usr/share/nginx/html/404.html"
    ports:
      - 80:80